### ISSUE TITLE
Code for Baselines

### ISSUE THREAD

**Issue by sriharshakoribille** [NACLab/robust-active-inference#1]
Hi, thank you for releasing such a great work on Active Inference. 
Do you plan on releasing the code for the active Inference baselines used with your modifications to continuous action space(DAIVPG-G and Himst-G)?

**Comment by rxng8** [comment]
Hi @sriharshakoribille ,

thank you for your interest in this work. Yes, we do have plan to release the baselines implementations (DAIVPG-G and Himst-G) in the future! We will let you know when they are public.

Best,
Viet
